package specter

type ArtifactID string

// Artifact represents a result or output generated by a SpecificationProcessor.
// An artifact is a unit of data or information produced as part of the processing workflow.
// It can be a transient, in-memory object, or it might represent more permanent entities such as
// files on disk, records in a database, deployment units, or other forms of data artifacts.
type Artifact interface {
	// ID is a unique identifier of the artifact, which helps in distinguishing and referencing
	// the artifact within a processing context.
	ID() ArtifactID
}
