package specter

type DefaultSourceLoadingStage = sourceLoadingStage
type DefaultUnitLoadingStage = unitLoadingStage
type DefaultUnitProcessingStage = unitProcessingStage
type DefaultArtifactProcessingStage = artifactProcessingStage
